## Open config file and catalog

An example to load a configuration file and a catalog file

In [43]:
%load_ext autoreload
%autoreload 2
from paidiverpy import Paidiverpy
from paidiverpy.pipeline import Pipeline
from paidiverpy.open_layer import OpenLayer
from paidiverpy.config import Configuration
from paidiverpy.catalog_parser import CatalogParser

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Using paidiverpy class

In [44]:
# Instantiate the class
# You may need to change the parameters on the config_1.yaml file for the correct paths on your computer
paidiver = Paidiverpy(config_file_path='../config_files/config_1.yaml')

In [45]:
# See the type of config
type(paidiver.config)

paidiverpy.config.Configuration

In [46]:
# Print config as json
paidiver.config

{
    "general": {
        "input_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen",
        "output_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/data",
        "catalog_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_jen.csv",
        "catalog_type": "CSV",
        "append_data_to_catalog": "/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/scidata_20180610.csv",
        "image_type": "JPG",
        "sampling_mode": "fixed",
        "sampling_limits": 30,
        "convert_autoscale": true,
        "convert_bits": 8,
        "convert_to": "RGB",
        "convert_channel_selector": -1,
        "name": "raw",
        "step_name": "Open"
    },
    "steps": []
}

In [47]:
# See catalog information
paidiver.get_catalog()

    ID  Unnamed: 0_x  ... flag                              point
0    0           430  ...    0  POINT (-153.60531587 11.25172554)
1    1           431  ...    0  POINT (-153.60531372 11.25171832)
2    2           432  ...    0   POINT (-153.60531259 11.2517135)
3    3           433  ...    0  POINT (-153.60531313 11.25170837)
4    4           434  ...    0  POINT (-153.60531414 11.25170299)
..  ..           ...  ...  ...                                ...
95  95           525  ...    0  POINT (-153.60449404 11.25151183)
96  96           526  ...    0  POINT (-153.60448659 11.25151015)
97  97           527  ...    0  POINT (-153.60447568 11.25150874)
98  98           528  ...    0   POINT (-153.60446358 11.2515081)
99  99           529  ...    0  POINT (-153.60445029 11.25150777)

[100 rows x 38 columns]

## Using other processing classes, like OpenLayer

In [48]:
open_layer = OpenLayer(config_file_path='../config_files/config_1.yaml')

In [49]:
# Print config as json
open_layer.config

{
    "general": {
        "input_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen",
        "output_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/data",
        "catalog_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_jen.csv",
        "catalog_type": "CSV",
        "append_data_to_catalog": "/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/scidata_20180610.csv",
        "image_type": "JPG",
        "sampling_mode": "fixed",
        "sampling_limits": 30,
        "convert_autoscale": true,
        "convert_bits": 8,
        "convert_to": "RGB",
        "convert_channel_selector": -1,
        "name": "raw",
        "step_name": "Open"
    },
    "steps": []
}

In [50]:
# See catalog information
# The catalog in this case may have more information because the openlayer class extracts the exif information from the files
open_layer.get_catalog()

    ID  Unnamed: 0_x  ... XResolution_y                                Artist
0    0           430  ...         300.0
1    1           431  ...         300.0
2    2           432  ...         300.0
3    3           433  ...         300.0
4    4           434  ...         300.0
..  ..           ...  ...           ...                                   ...
95  95           525  ...         300.0
96  96           526  ...         300.0
97  97           527  ...         300.0
98  98           528  ...         300.0
99  99           529  ...         300.0

[100 rows x 51 columns]

## Using configuration parsing

In [51]:
config = Configuration(config_file_path='../config_files/config_1.yaml')
config

{
    "general": {
        "input_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen",
        "output_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/data",
        "catalog_path": "/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_jen.csv",
        "catalog_type": "CSV",
        "append_data_to_catalog": "/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/scidata_20180610.csv",
        "image_type": "JPG",
        "sampling_mode": "fixed",
        "sampling_limits": 30,
        "convert_autoscale": true,
        "convert_bits": 8,
        "convert_to": "RGB",
        "convert_channel_selector": -1,
        "name": "raw",
        "step_name": "Open"
    },
    "steps": []
}

In this case, yu will not have access to the catalog, as it wasnot parsed yet

# Parse only the catalog

In [52]:
# You need to pass the configuration file
catalog = CatalogParser(config=config)
catalog

    ID  Unnamed: 0_x  ... flag                              point
0    0           430  ...    0  POINT (-153.60531587 11.25172554)
1    1           431  ...    0  POINT (-153.60531372 11.25171832)
2    2           432  ...    0   POINT (-153.60531259 11.2517135)
3    3           433  ...    0  POINT (-153.60531313 11.25170837)
4    4           434  ...    0  POINT (-153.60531414 11.25170299)
..  ..           ...  ...  ...                                ...
95  95           525  ...    0  POINT (-153.60449404 11.25151183)
96  96           526  ...    0  POINT (-153.60448659 11.25151015)
97  97           527  ...    0  POINT (-153.60447568 11.25150874)
98  98           528  ...    0   POINT (-153.60446358 11.2515081)
99  99           529  ...    0  POINT (-153.60445029 11.25150777)

[100 rows x 38 columns]